import type { Metadata } from "next";
import "./globals.css";
import Outfit from "next/font/local";

const outfit = Outfit({
  src: "/fonts/Outfit-VariableFont_wght.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Movies App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
